import Head from 'next/head';
import ComingSoon from '../app/components/ComingSoon';

export default function Home() {
	return (
		<>
			<Head>
				<title>RareSense - Coming Soon!</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />

				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link rel='preconnect' href='https://fonts.gstatic.com' crossorigin />
				<link
					href='https://fonts.googleapis.com/css2?family=Red+Hat+Text:wght@400;700&display=swap'
					rel='stylesheet'
				/>
			</Head>

			<ComingSoon />
		</>
	);
}
